version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
